[package]
name = "supervisors"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
axum = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
hyper = "1.6.0"
