name: Release

on:
  push:
    tags:
      - "v*.*.*" # triggers on version tags like v1.0.0

jobs:
  build:
    name: Build Binaries
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            ext: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: .exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install packaging tools (Linux only)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools rpm
          cargo install cargo-deb
          cargo install cargo-generate-rpm

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build .deb package (only for glibc Linux)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo deb --no-build --target ${{ matrix.target }}

      - name: Build .rpm package (only for glibc Linux)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo generate-rpm --target ${{ matrix.target }}

      - name: Package binary
        shell: pwsh
        run: |
          $Target = "${{ matrix.target }}"
          $Ext = "${{ matrix.ext }}"
          $BinaryName = "supervisors$Ext"
          $OutZip = "supervisors-$Target.zip"
          $Dist = "dist"

          New-Item -ItemType Directory -Force -Path $Dist | Out-Null
          Copy-Item "target/$Target/release/$BinaryName" "$Dist/"

          if ($IsWindows) {
            Compress-Archive -Path "$Dist/$BinaryName" -DestinationPath "$Dist/$OutZip"
          } else {
            & zip "$Dist/$OutZip" "$Dist/$BinaryName"
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supervisors-${{ matrix.target }}
          path: |
            dist/supervisors-${{ matrix.target }}.zip
            target/debian/*.deb
            target/generate-rpm/*.rpm
          if-no-files-found: ignore

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.zip, artifacts/**/*.deb, artifacts/**/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
